# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ConsentManagerDemo_ObjC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConsentManagerDemo_ObjC
	pod "TealiumIOS", "5.4.0"
end
