# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WatchOS_Sample_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchOS_Sample_Swift
	pod	"TealiumIOS", "~> 5.6.3"

end

